import { TypographyOptions } from "@mui/material/styles/createTypography";

export const typography: TypographyOptions = {
  button: {
    textTransform: "capitalize",
    width: "159px",
    height: "54px",
    borderRadius: "40px",
    fontFamily: "Nunito Sans, sans-serif",
    fontSize: "20px",
    fontWeight: 700,
    textDecoration: "none",
    lineHeight: "150%",
    margin: "8px",
  },
  h1: {
    fontFamily: "Nunito Sans, sans-serif",
    fontWeight: 800,
    style: "normal",
    fontSize: "64px",
    lineHeight: "64px",
    letterSpacing: "0px",
    marginBottom: "25px",
    color: "#333333",
  },
  h2: {
    fontFamily: "Nunito sans, sans-serif",
    fontWeight: 600,
    fontSize: "32px",
    lineHeight: "62.4px",
    marginBottom: "25px",
    color: "#ffffff",
  },
  h3: {
    fontFamily: "Nunito Sans, sans-serif",
    fontWeight: 800,
    fontSize: "32px",
    lineHeight: "42px",
    letterSpacing: "0px",
    marginBottom: "25px",
  },
  h4: {
    fontFamily: "Nunito Sans, sans-serif",
    fontSize: "18px",
    fontWeight: 400,
    textDecoration: "none",
    color: "#ffffff",
    lineHeight: "30px",
    letterSpacing: "0.18px",
  },
  h5: {
    fontFamily: "Nunito Sans, sans-serif",
    fontSize: "20px",
    fontWeight: 400,
    textDecoration: "none",
    color: "#333333",
    lineHeight: "30px",
    letterSpacing: "0.18px",
  },
  body1: {
    fontFamily: "Nunito Sans, sans-serif",
    fontSize: "16px",
    fontWeight: 500,
    textDecoration: "none",
    color: "white",
    lineHeight: "24px",
    letterSpacing: "0.14px",
  },
  body2: {
    fontFamily: "Nunito Sans, sans-serif",
    fontSize: "16px",
    fontWeight: 400,
    textDecoration: "none",
    color: "#ffffff",
    lineHeight: "24px",
    letterSpacing: "0.14px",
  },
};
